node {
  def app
  def commit_id
  def REGISTRY = 'harbor.idtplateer.com'
  def HARBOR_NAMESPACE = 'guestbook'
  def APP_NAME = 'gb-frontend'
  def HARBOR_CREDENTIAL ='harbor-id'
  
  stage('preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"
    commit_id = readFile('.git/commit-id').trim()
  }
   
  //dockerfile기반 빌드하는 stage ,git 베이스 소스기준으로 ./guestbook 폴더에 dockerfile 이 있어야 함
  //guestbook 프로젝트에 appName 이 guestbook 으로 이미지가 올라감
  stage('build image') { 
    app = docker.build("$REGISTRY/$HARBOR_NAMESPACE/$APP_NAME", "./guestbook")    
  }

  //docker image를 push하는 stage
  //docker.withRegistry 에 harbor-id 는 앞서 설정한 harbor credentials의 ID
  stage('build and push image') {
    docker.withRegistry("https://$REGISTRY", "$HARBOR_CREDENTIAL") {
      if (app) {
        app.push("latest")
      }
    }                                     
  }
  
  stage('helm chart download and test') {
    sh 'git clone https://github.com/kin3303/guestbook.git'
    sh 'helm lint guestbook'
    sh '''#!/bin/bash 
    sudo tee  .yamllint > /dev/null <<- _EOF_ 
    extends: default
    rules:
      line-length:
        max: 150
      trailing-spaces:
        level: warning
      key-duplicates:
        level: error
    _EOF_''' 
  }
}
