node {
  def app
  def commit_id
  
  environment {
    REGISTRY = 'harbor.idtplateer.com'
    HARBOR_NAMESPACE = 'guestbook'
    APP_NAME = 'gb-frontend'
    HARBOR_CREDENTIAL ='harbor-id'
  }  
  
  stage('preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"
    commit_id = readFile('.git/commit-id').trim()
  }
   
  //dockerfile기반 빌드하는 stage ,git 베이스 소스기준으로 ./guestbook 폴더에 dockerfile 이 있어야 함
  //guestbook 프로젝트에 appName 이 guestbook 으로 이미지가 올라감
  stage('build docker image') { 
    app = docker.build("$REGISTRY/$HARBOR_NAMESPACE/$APP_NAME", "./guestbook")    
  }

  //docker image를 push하는 stage
  //docker.withRegistry 에 harbor-id 는 앞서 설정한 harbor credentials의 ID
  stage('push docker image') {
    docker.withRegistry('https://$REGISTRY', $HARBOR_CREDENTIAL) {
      if (app) {
        app.push("latest")
      }
    }                                     
  }  
}
